### ISSUE TITLE
Export map to image

### ISSUE THREAD

**Issue by KasperZutterman** [oSoc20/SerendipityEngine#36]
Add the functionality to download the map as an image.
Available solutions:
- http://html2canvas.hertzen.com/
- https://stackoverflow.com/questions/923885/capture-html-canvas-as-gif-jpg-png-pdf

**Comment by dormalexis** [comment]
I had a look on it. 

The problem with first solution is that it will render a canvas based on the html we have, it means also with downloads button, fit map, etc.. And we should add in the html for the top and the bottom of the image to follow Louis's design. Maybe not the best idea

For the second, it works well if we have only one canvas and transform in image. But what about adding images ? I saw document.write was used to put the image generated in the html but it's not really what we want..

I'm having a look on that to generate the image which follows Louis's design that could let us free of having our html file and the file we want to render without having the need to link both : in this way we could have totally different image than from the website (regarding to layout)
