### ISSUE TITLE
Select map provider

### ISSUE THREAD

**Issue by KasperZutterman** [oSoc20/SerendipityEngine#4]
- Leaflet: https://blog.mestwin.net/angular-8-with-leaflet-map-geocoding-using-nominatim-api/
- OpenStreetMap: https://medium.com/@balramchavan/using-openstreetmap-inside-angular-v6-3d42cbf03e57

**Comment by hdelva** [comment]
Software-wise, I'd recommend either leaflet or [Mapbox GL](https://docs.mapbox.com/mapbox-gl-js/api/). Leaflet is easier to use, Mapbox GL is more efficient. I doubt the visualizations you'll end up doing are complex enough to notice a difference though.

If you're looking for tile providers, I'm pretty happy with [Jawg](https://www.jawg.io/en/). It's very configurable, and their free tier is actually pretty generous. Another good option is Mapbox of course.

**Comment by KasperZutterman** [comment]
#12 
Mapbox was selected
